// Mocks generated by Mockito 5.0.16 from annotations
// in moviedb_flutter/test/unit_test/storage/service_api_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:moviedb_flutter/application/business_logic/model/movie/MovieModel.dart'
    as _i2;
import 'package:moviedb_flutter/application/service/ServiceApi.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMovieModel_0 extends _i1.Fake implements _i2.MovieModel {}

/// A class which mocks [ServiceApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceApi extends _i1.Mock implements _i3.ServiceApi {
  MockServiceApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MovieModel> serviceApi(String? value) =>
      (super.noSuchMethod(Invocation.method(#serviceApi, [value]),
              returnValue: Future<_i2.MovieModel>.value(_FakeMovieModel_0()))
          as _i4.Future<_i2.MovieModel>);
  @override
  _i2.MovieModel parseModel(String? responseBody) =>
      (super.noSuchMethod(Invocation.method(#parseModel, [responseBody]),
          returnValue: _FakeMovieModel_0()) as _i2.MovieModel);
  @override
  String toString() => super.toString();
}
