name: moviedb_flutter
description: A MovieDB API Application builted with Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  provider: 6.1.2
  http: 0.13.6
  json_annotation: 4.8.1
  mobx: 2.3.2
  flutter_mobx: 2.2.0+2
  path_provider: 2.1.1
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true

